---
title: "cleaning the pitching projections 2025"
author: "William Foote"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# zips <- read.csv("pitch_zips.csv")
# steamer <- read.csv("pitch_steamer.csv")
# dc <- read.csv("pitch_depthcharts.csv")
atc <- read.csv("~/Documents/GitHub/fantasy_baseball_draft_bot/R-stuff/2025/data/patc_2025.csv")
# bat <- read.csv("pitch_thebat.csv")

# all_dfs <- list(bat = bat, atc = atc, dc = dc, zips = zips, steamer = steamer)
```

# Just looking

## Head

```{r}
# head(zips)
# head(steamer)
# head(dc)
head(atc)
# head(bat)
```

## Make SVHD category in atc and dc

```{r}
# dc$SVHD <- with(dc, SV + HLD)
atc$SVHD <- with(atc, SV + HLD)
```

## Impute Quality Starts using cool function

```{r}
# pqs <- function(x) {
#   if (x$GS < 10) { # Probably not a starter
#     p_qs <- 0
#   } else {
#     W <- x$W
#     L <- x$L
#     G <- x$G
#     IP <- x$IP
#     ER <- x$ER
#     intercept <- 0.08434435
#     x_w <- 0.17309031
#     x_l <- -0.20007936
#     x_g <- -0.09077845
#     x_ip <- 0.06996364
#     x_er <- 0.03699742
#     p_qs <- intercept + W*x_w + L*x_l + G*x_g + IP*x_ip + ER*x_er
#   }
#   p_qs
# }
# 
# 
# df_lengths <- c(nrow(zips), nrow(steamer), nrow(dc), nrow(atc))
# 
# for(i in seq_len(df_lengths[1])) {
#   zips$QS[[i]] <- pqs(zips[i, ]) 
# }
# 
# for(i in seq_len(df_lengths[2])) {
#   steamer$QS[[i]] <- pqs(steamer[i, ]) 
# }
# 
# for(i in seq_len(df_lengths[3])) {
#   dc$QS[[i]] <- pqs(dc[i, ]) 
# }
# 
# for(i in seq_len(df_lengths[4])) {
#   atc$QS[[i]] <- pqs(atc[i, ]) 
# }
```

## Making 6 data frames for 6 pitching categories

### Helpers

```{r}
cats <- c("IP", "SO", "QS", "ERA", "WHIP", "SVHD")
order_small_to_large <- c("bat", "atc", "dc", "zips", "steamer")

me1 <- function(x, y, cat = "QS", by = "playerid") { # If i were 1
  temp <- merge(x[, c("Name", by, cat)], y[, c(by, cat)], by = by)
  temp
}

me2 <- function(x, y, cat = "QS", by = "playerid") { # If i were greater than 1
  temp <- merge(x, y[, c(by, cat)], by = by)
  temp
}
```


### The Cleaning (didnt use in 2022 data)

```{r}
# temp_qs <- me1(steamer, zips)
# tqs2 <- me2(temp_qs, dc)
# tqs3 <- me2(tqs2, atc)
# tqs4 <- me2(tqs3, bat)
# tqs4
# 
# temp_ip <- me1(steamer, zips, cat = "IP")
# tip2 <- me2(temp_ip, dc, cat = "IP")
# tip3 <- me2(tip2, atc, cat = "IP")
# tip4 <- me2(tip3, bat, cat = "IP")
# tip4
# 
# temp_so <- me1(steamer, zips, cat = "SO")
# tso2 <- me2(temp_so, dc, cat = "SO")
# tso3 <- me2(tso2, atc, cat = "SO")
# tso4 <- me2(tso3, bat, cat = "SO")
# tso4
# 
# temp_era <- me1(steamer, zips, cat = "ERA")
# tera2 <- me2(temp_era, dc, cat = "ERA")
# tera3 <- me2(tera2, atc, cat = "ERA")
# tera4 <- me2(tera3, bat, cat = "ERA")
# tera4
# 
# temp_whip <- me1(steamer, zips, cat = "WHIP")
# twhip2 <- me2(temp_whip, dc, cat = "WHIP")
# twhip3 <- me2(twhip2, atc, cat = "WHIP")
# twhip4 <- me2(twhip3, bat, cat = "WHIP")
# twhip4
# 
# temp_svhd <- me1(atc, dc, cat = "SVHD") 
# good_indices <- temp_svhd$playerid %in% twhip4$playerid # This is because we didn't cut down to the right dimensions
# temp_svhd <- temp_svhd[good_indices, ]
# temp_svhd
# 
# pitch <- cbind(tip4[, c(1, 2)], IP = apply(tip4[, c(-1, -2)], 1, mean))
# pitch <- cbind(pitch, SO = cbind(tso4[, c(1, 2)], SO = apply(tso4[, c(-1, -2)], 1, mean))[, -c(1, 2)])
# pitch <- cbind(pitch, QS = cbind(tqs4[, c(1, 2)], QS = apply(tqs4[, c(-1, -2)], 1, mean))[, -c(1, 2)])
# pitch <- cbind(pitch, ERA = cbind(tera4[, c(1, 2)], ERA = apply(tera4[, c(-1, -2)], 1, mean))[, -c(1, 2)])
# pitch <- cbind(pitch, WHIP = cbind(twhip4[, c(1, 2)], WHIP = apply(twhip4[, c(-1, -2)], 1, mean))[, -c(1, 2)])
# pitch <- cbind(pitch, SVHD = cbind(temp_svhd[, c(1, 2)], SVHD = apply(temp_svhd[, c(-1, -2)], 1, mean))[, -c(1, 2)])
# pitch
```

# Cleaning 2022

```{r}
atc$wERA <- atc$ERA * atc$IP
atc$wWHIP <- atc$WHIP * atc$IP

pitch <- atc %>%
  select(Name, Team, PlayerId, IP, SO, QS, wERA, wWHIP, ERA, WHIP, SVHD)
```


# Now adding z-scores

## Z score function

```{r}
z_score <- function(x) {
  x <- as.numeric(x)
  m <- mean(x, na.rm = TRUE)
  s <- sd(x, na.rm = TRUE)
  z <- (x - m) / s
  z
}
```

## Use the z-score function

```{r}
pitching_2 <- pitch
temp <- apply(pitching_2[, -c(1:3)], 2, z_score)
pitching_2 <- cbind(pitching_2[, c(1, 2, 3)], temp)
pitching_2$ERA <- -1 * pitching_2$ERA
pitching_2$WHIP <- -1 * pitching_2$WHIP
sums <- apply(pitching_2[, -c(1, 2, 3)], 1, sum)
pitching_3 <- pitching_2
pitching_3$pr <- sums
head(pitching_3)
pitching_ordered <- pitching_3[order(pitching_3$pr, decreasing = TRUE), ]
# Repeat the calculations on only the top 300
# Normalize to this number to compare against batters better
temp <- left_join(pitching_ordered[1:300, 1:3], pitch, by = c("Name", 'Team', 'PlayerId'))
pitching_2 <- temp
temp <- apply(pitching_2[, -c(1:3)], 2, z_score)
pitching_2 <- cbind(pitching_2[, c(1, 2, 3)], temp)
pitching_2$ERA <- -1 * pitching_2$ERA
pitching_2$WHIP <- -1 * pitching_2$WHIP
sums <- apply(pitching_2[, -c(1, 2, 3)], 1, sum)
pitching_3 <- pitching_2
pitching_3$pr <- sums
head(pitching_3)
pitching_ordered <- pitching_3[order(pitching_3$pr, decreasing = TRUE), ]
pitching_ordered$rank <- 1:300
pitching_ordered$pos <- 'SP'
```

## Check to see if we did it right

```{r}
head(pitching_3[with(pitching_3, order(pitching_3$pr, decreasing = TRUE)), ])
```

```{r}
write.csv(pitching_ordered, "patc_pr.csv")
```

